# frozen_string_literal: true

require "test_helper"

class ValpoCaddyRendererTest < Minitest::Test
  def test_supports_container_static_and_verification_routes
    renderer = Valpo::Caddy::Renderer.new

    output = renderer.render([
      {hostname: "hello.example.com", kind: "container", upstream: "valpo-hello:3000"},
      {hostname: "static.example.com", kind: "static", root: "/var/lib/valpo/releases/static"},
      {hostname: "verify.example.com", kind: "verification", token: "abc123"}
    ])

    assert_includes output, "hello.example.com {\n  reverse_proxy valpo-hello:3000\n}"
    assert_includes output, "static.example.com {\n  root * /var/lib/valpo/releases/static\n  file_server\n}"
    assert_includes output, "verify.example.com {\n  respond /.well-known/valpo-verification/abc123 \"abc123\" 200\n}"
  end

  def test_empty_routes_render_valid_generated_file
    renderer = Valpo::Caddy::Renderer.new

    assert_equal "# Generated by Valpo. Do not edit by hand.\n", renderer.render([])
  end
end
