# frozen_string_literal: true

require "test_helper"

class ValpoCaddyRendererTest < Minitest::Test
  def test_supports_container_verification_and_restricted_proxy_routes
    renderer = Valpo::Caddy::Renderer.new

    output = renderer.render([
      {hostname: "hello.example.com", kind: "container", upstream: "valpo-hello:3000"},
      {hostname: "verify.example.com", kind: "verification", token: "abc123"},
      {
        hostname: "github.apps.example.com",
        kind: "restricted_proxy",
        upstream: "127.0.0.1:7092",
        path: "/integrations/github"
      }
    ])

    assert_includes output, "hello.example.com {\n\treverse_proxy valpo-hello:3000\n}"
    assert_includes output, "verify.example.com {\n\trespond /.well-known/valpo-verification/abc123 \"abc123\" 200\n}"
    assert_includes output, [
      "github.apps.example.com {",
      "\troute {",
      "\t\t@allowed path /integrations/github /integrations/github/*",
      "\t\treverse_proxy @allowed 127.0.0.1:7092",
      "\t\trespond 404",
      "\t}",
      "}"
    ].join("\n")
  end

  def test_empty_routes_render_valid_generated_file
    renderer = Valpo::Caddy::Renderer.new

    assert_equal "# Generated by Valpo. Do not edit by hand.\n", renderer.render([])
  end
end
