source "https://rubygems.org"
ruby "4.0.6"
gem "sinatra", "~> 4.2"
gem "puma", "~> 7.0"
gem "sequel", "~> 5.0"
gem "pg", "~> 1.6"
gem "rack-session", "~> 2.1"
group :test do
  gem "minitest", "~> 5.0"
  gem "rack-test", "~> 2.2"
end
