#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)
require "bundler/setup"

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))

require "optparse"
require "valpo"

options = {}
OptionParser.new do
  it.banner = "Usage: valpo-migrate [options]"
  it.on("--config PATH", "Path to valpo.yml") { options[:config] = it }
end.parse!(ARGV)

config = Valpo::Config.load(path: options[:config])
Valpo.config = config
begin
  Valpo::Database.connect(config)
  Valpo::Migrator.run
  schema = Valpo::ReleaseMetadata.current.validate_database!
  puts "Migrated Valpo database to schema #{schema}"
ensure
  Valpo::Database.disconnect
end
