#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)
require "bundler/setup"
$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "valpo"

begin
  token = Valpo::Credentials::Bootstrap.new.call
  puts token if token
rescue Valpo::ValidationError, Valpo::ConflictError => e
  warn e.message
  exit 1
end
