#!/usr/bin/env ruby
# frozen_string_literal: true

prompt = ARGV.join(" ")

if prompt.match?(/username/i)
  puts "x-access-token"
elsif prompt.match?(/password/i)
  puts ENV.fetch("VALPO_GIT_ASKPASS_TOKEN")
else
  exit 1
end
