#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)
require "bundler/setup"

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))

require "optparse"
require "rackup"
require "valpo"

options = {}
OptionParser.new do |parser|
  parser.banner = "Usage: valpo-api [options]"
  parser.on("--config PATH", "Path to valpo.yml") { |path| options[:config] = path }
  parser.on("--migrate", "Run migrations before booting") { options[:migrate] = true }
end.parse!(ARGV)

config = Valpo::Config.load(path: options[:config])
Valpo::Boot.run(config: config, migrate: options[:migrate])

Rackup::Server.start(
  app: Valpo::API::App,
  server: "puma",
  Host: config.api_host,
  Port: config.api_port
)
