#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)
require "bundler/setup"

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))

require "optparse"
require "valpo"

options = {}
OptionParser.new do
  it.banner = "Usage: valpo-worker [options]"
  it.on("--config PATH", "Path to valpo.yml") { options[:config] = it }
  it.on("--once", "Process at most one job and exit") { options[:once] = true }
  it.on("--migrate", "Run migrations before starting") { options[:migrate] = true }
end.parse!(ARGV)

config = Valpo::Config.load(path: options[:config])
Valpo::Boot.run(config:, migrate: options[:migrate])

worker = Valpo::Jobs::Worker.new(config:, poll_interval: config.worker_poll_interval)
Signal.trap("TERM") { worker.stop }
Signal.trap("INT") { worker.stop }
begin
  worker.run(once: options[:once])
rescue Valpo::ConflictError => e
  warn "valpo-worker: #{e.message}"
  exit 1
end
