# frozen_string_literal: true

module Valpo
  module Caddy
    class Renderer
      HEADER = "# Generated by Valpo. Do not edit by hand."

      def render(routes)
        ([HEADER] + routes.map { render_route(it) }).join("\n\n") + "\n"
      end

      private

      def render_route(route)
        hostname = route.fetch(:hostname)
        kind = route.fetch(:kind).to_s

        case kind
        when "container"
          upstream = route.fetch(:upstream)
          "#{hostname} {\n\treverse_proxy #{upstream}\n}"
        when "verification"
          token = route.fetch(:token)
          path = Valpo::Domains::ReachabilityVerifier.challenge_path(token)
          "#{hostname} {\n\trespond #{path} \"#{token}\" 200\n}"
        when "restricted_proxy"
          upstream = route.fetch(:upstream)
          path = route.fetch(:path)
          [
            "#{hostname} {",
            "\troute {",
            "\t\t@allowed path #{path} #{path}/*",
            "\t\treverse_proxy @allowed #{upstream}",
            "\t\trespond 404",
            "\t}",
            "}"
          ].join("\n")
        else
          raise Valpo::ValidationError, "Unsupported Caddy route kind: #{kind}"
        end
      end
    end
  end
end
