# frozen_string_literal: true

module Valpo
  module Caddy
    class Renderer
      HEADER = "# Generated by Valpo. Do not edit by hand."

      def render(routes)
        ([HEADER] + routes.map { render_route(it) }).join("\n\n") + "\n"
      end

      private

      def render_route(route)
        hostname = route.fetch(:hostname)
        kind = route.fetch(:kind).to_s

        case kind
        when "container"
          upstream = route.fetch(:upstream)
          "#{hostname} {\n  reverse_proxy #{upstream}\n}"
        when "static"
          root = route.fetch(:root)
          "#{hostname} {\n  root * #{root}\n  file_server\n}"
        when "verification"
          token = route.fetch(:token)
          path = Valpo::Domains::ReachabilityVerifier.challenge_path(token)
          "#{hostname} {\n  respond #{path} \"#{token}\" 200\n}"
        when "restricted_proxy"
          upstream = route.fetch(:upstream)
          path = route.fetch(:path)
          <<~CADDY.chomp
            #{hostname} {
              route {
                @allowed path #{path} #{path}/*
                reverse_proxy @allowed #{upstream}
                respond 404
              }
            }
          CADDY
        else
          raise Valpo::ValidationError, "Unsupported Caddy route kind: #{kind}"
        end
      end
    end
  end
end
